# Generated by Django 5.2.9 on 2026-01-12 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="partner",
            options={"ordering": ["nom"]},
        ),
        migrations.AlterUniqueTogether(
            name="partner",
            unique_together={("entreprise", "email")},
        ),
    ]
