# Generated by Django 5.2.9 on 2026-01-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("partners", "0002_alter_partner_options_alter_partner_unique_together"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partner",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["entreprise", "type"], name="partners_pa_entrepr_085c7d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="partner",
            index=models.Index(
                fields=["entreprise", "nom"], name="partners_pa_entrepr_f371b2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="partner",
            constraint=models.UniqueConstraint(
                fields=("email",), name="unique_email_per_entreprise"
            ),
        ),
    ]
