# Generated by Django 5.2.6 on 2026-01-04 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="nom",
            field=models.CharField(
                choices=[
                    ("SUPER_ADMIN", "Super_Admin"),
                    ("ADMIN", "Administrateur"),
                    ("COMPTABLE", "Comptable"),
                    ("VENTES", "Ventes"),
                ],
                default="VENTES",
                max_length=50,
            ),
        ),
    ]
