# Generated by Django 6.0 on 2026-01-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.FileField(blank=True, null=True, upload_to="profiles/"),
        ),
    ]
