# Generated by Django 5.2.6 on 2026-01-04 10:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Depense",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("categorie", models.CharField(db_index=True, max_length=100)),
                ("description", models.TextField()),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("type", models.CharField(db_index=True, max_length=50)),
                (
                    "justificatif",
                    models.FileField(blank=True, null=True, upload_to="factures/"),
                ),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="depenses",
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["entreprise", "categorie"],
                        name="finance_dep_entrepr_166c88_idx",
                    ),
                    models.Index(
                        fields=["entreprise", "type"],
                        name="finance_dep_entrepr_262145_idx",
                    ),
                ],
            },
        ),
    ]
