# Generated by Django 5.2.6 on 2026-01-09 10:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0003_unitemesure_vente_prix_vente_alter_vente_entreprise_and_more",
        ),
        ("finance", "0001_initial"),
        ("partners", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantite", models.IntegerField()),
                (
                    "prix_achat",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("date_entree", models.DateField(db_index=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.entreprise",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        limit_choices_to={"type": "fournisseur"},
                        on_delete=django.db.models.deletion.PROTECT,
                        to="partners.partner",
                    ),
                ),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stocks",
                        to="commerce.produit",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["entreprise", "created_at"],
                        name="finance_sto_entrepr_9ea8c9_idx",
                    )
                ],
            },
        ),
    ]
