# Generated by Django 5.2.6 on 2026-01-09 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0003_unitemesure_vente_prix_vente_alter_vente_entreprise_and_more",
        ),
        ("finance", "0002_stock"),
        ("partners", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="stock",
            name="finance_sto_entrepr_9ea8c9_idx",
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["entreprise", "date_entree"],
                name="finance_sto_entrepr_e71c50_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stock",
            index=models.Index(
                fields=["entreprise", "fournisseur"],
                name="finance_sto_entrepr_fbcc5f_idx",
            ),
        ),
    ]
