# Generated by Django 5.2.6 on 2026-01-09 12:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0003_unitemesure_vente_prix_vente_alter_vente_entreprise_and_more",
        ),
        ("finance", "0003_remove_stock_finance_sto_entrepr_9ea8c9_idx_and_more"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="depense",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.entreprise",
            ),
        ),
        migrations.CreateModel(
            name="Conditionnement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("nom", models.CharField(max_length=50)),
                ("quantite", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "produit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conditionnements",
                        to="commerce.produit",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
