# Generated by Django 5.2.6 on 2026-01-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0004_alter_depense_entreprise_conditionnement"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="conditionnement",
            name="produit",
        ),
        migrations.RemoveIndex(
            model_name="depense",
            name="finance_dep_entrepr_166c88_idx",
        ),
        migrations.RemoveField(
            model_name="depense",
            name="categorie",
        ),
        migrations.AddIndex(
            model_name="depense",
            index=models.Index(
                fields=["entreprise"], name="finance_dep_entrepr_23b869_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Conditionnement",
        ),
    ]
