# Generated by Django 5.2.9 on 2026-01-13 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0005_remove_conditionnement_produit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="quantite",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
