# Generated by Django 5.2.6 on 2026-01-04 10:11

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonnement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("type", models.CharField(db_index=True, max_length=50)),
                ("date_debut", models.DateField(db_index=True)),
                ("date_fin", models.DateField(db_index=True)),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                ("status", models.CharField(db_index=True, max_length=20)),
                ("fonctionnalites", models.JSONField(default=list)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonnements",
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
