# Generated by Django 5.2.9 on 2026-01-13 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.entreprise",
            ),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("expired", "Expired")],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="abonnement",
            name="type",
            field=models.CharField(
                choices=[
                    ("basic", "BASIC"),
                    ("medium", "MEDIUM"),
                    ("premium", "PREMIUM"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="abonnement",
            index=models.Index(
                fields=["entreprise", "created_at"],
                name="subscriptio_entrepr_c0d26a_idx",
            ),
        ),
    ]
