# Generated by Django 5.2.10 on 2026-01-24 14:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "subscriptions",
            "0002_alter_abonnement_entreprise_alter_abonnement_status_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abonnement",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.entreprise",
            ),
        ),
    ]
