# Generated by Django 5.2.6 on 2026-01-05 10:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.CharField(choices=[('Ventes', 'Ventes'), ('Produits', 'Produits'), ('Depenses', 'Dépenses'), ('Abonnements', 'Abonnements')], max_length=50)),
                ('format', models.CharField(choices=[('CSV', 'CSV'), ('Excel', 'Excel'), ('PDF', 'PDF')], max_length=10)),
                ('file_url', models.FileField(upload_to='exports/')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
