# Generated by Django 5.2.6 on 2026-01-09 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0002_alter_produit_entreprise_categorie"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UniteMesure",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=10, unique=True)),
                ("nom", models.CharField(max_length=50)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("poids", "Poids"),
                            ("volume", "Volume"),
                            ("unite", "Unité"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "facteur_conversion",
                    models.DecimalField(decimal_places=4, default=1, max_digits=10),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="vente",
            name="prix_vente",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="entreprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.entreprise",
            ),
        ),
        migrations.AddField(
            model_name="produit",
            name="mesure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="produits",
                to="commerce.unitemesure",
            ),
        ),
    ]
