# Generated by Django 5.2.6 on 2026-01-09 13:36

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commerce",
            "0003_unitemesure_vente_prix_vente_alter_vente_entreprise_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="mesure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg", "Kilogramme"),
                    ("l", "Litre"),
                    ("unite", "Unité"),
                    ("m", "Mètre"),
                    ("boite", "Boîte"),
                    ("paquet", "Paquet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddConstraint(
            model_name="categorie",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("nom"),
                models.F("entreprise"),
                name="unique_categorie_per_entreprise_ci",
            ),
        ),
        migrations.DeleteModel(
            name="UniteMesure",
        ),
    ]
