# Generated by Django 5.2.6 on 2026-01-09 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0004_alter_produit_mesure_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="categorie",
            name="unique_categorie_per_entreprise_ci",
        ),
    ]
