# Generated by Django 5.2.6 on 2026-01-09 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0005_remove_categorie_unique_categorie_per_entreprise_ci"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="mesure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("kg", "Kilogramme"),
                    ("L", "Litre"),
                    ("unite", "Unité"),
                    ("m", "Mètre"),
                    ("boite", "Boîte"),
                    ("paquet", "Paquet"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="produit",
            name="quantite",
            field=models.PositiveIntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
