# Generated by Django 5.2.6 on 2026-01-10 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0007_refactor_vente"),
    ]

    operations = [
        migrations.AlterField(
            model_name="produit",
            name="mesure",
            field=models.CharField(
                blank=True,
                choices=[
                    ("t", "Tonne"),
                    ("kg", "Kilogramme"),
                    ("hg", "Hectogramme"),
                    ("g", "Gramme"),
                    ("mg", "Milligramme"),
                    ("hL", "Hectolitre"),
                    ("L", "Litre"),
                    ("mL", "Millilitre"),
                    ("m", "Mètre"),
                    ("cm", "Centimètre"),
                    ("mm", "Millimètre"),
                    ("unite", "Unité"),
                    ("paire", "Paire"),
                    ("piece", "Pièce"),
                    ("carton", "Carton"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="vente",
            name="prix_vente",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=10, null=True
            ),
        ),
    ]
