# Generated by Django 5.2.9 on 2026-01-12 14:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0008_alter_produit_mesure_alter_vente_prix_vente"),
        ("partners", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="venteproduit",
            name="entreprise",
        ),
        migrations.RemoveField(
            model_name="venteproduit",
            name="produit",
        ),
        migrations.RemoveField(
            model_name="venteproduit",
            name="vente",
        ),
        migrations.AddField(
            model_name="vente",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="vente",
            name="produit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="commerce.produit",
            ),
        ),
        migrations.AddField(
            model_name="vente",
            name="quantite",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AddIndex(
            model_name="vente",
            index=models.Index(
                fields=["client", "produit"], name="commerce_ve_client__c71757_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="vente",
            constraint=models.UniqueConstraint(
                fields=("entreprise", "client", "produit"),
                name="unique_vente_client_produit_par_entreprise",
            ),
        ),
        migrations.DeleteModel(
            name="VenteProduit",
        ),
    ]
