# Generated by Django 5.2.9 on 2026-01-13 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commerce", "0009_remove_venteproduit_entreprise_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="vente",
            name="unique_vente_client_produit_par_entreprise",
        ),
    ]
