# Generated by Django 5.2.6 on 2026-01-06 15:17

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoFormation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("titre", models.CharField(max_length=150)),
                ("url", models.URLField()),
                ("duree", models.IntegerField(help_text="Durée en secondes")),
                ("langue", models.CharField(max_length=20)),
                ("status", models.CharField(max_length=20)),
                ("date_genere", models.DateTimeField(auto_now_add=True)),
                (
                    "entreprise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_set",
                        to="tenants.entreprise",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["entreprise", "created_at"],
                        name="education_v_entrepr_01437c_idx",
                    )
                ],
            },
        ),
    ]
