# Generated by Django 5.2.9 on 2026-01-13 13:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0001_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="videoformation",
            name="education_v_entrepr_01437c_idx",
        ),
        migrations.RemoveField(
            model_name="videoformation",
            name="date_genere",
        ),
        migrations.AddField(
            model_name="videoformation",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("finance_personnelle", "Finance personnelle"),
                    ("gestion_entreprise", "Gestion entreprise"),
                    ("investissement", "Investissement"),
                    ("epargne_retraite", "Épargne & Retraite"),
                    ("cryptomonnaies", "Cryptomonnaies"),
                ],
                db_index=True,
                default="finance_personnelle",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Image de couverture de la formation",
                null=True,
                upload_to="formations/covers/",
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="description",
            field=models.TextField(
                default="", help_text="Description détaillée de la formation"
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("debutant", "Débutant"),
                    ("intermediaire", "Intermédiaire"),
                    ("avance", "Avancé"),
                ],
                default="debutant",
                max_length=15,
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="objectifs",
            field=models.TextField(
                blank=True,
                help_text="Objectifs pédagogiques (séparés par des tirets ou numérotés)",
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="pre_requis",
            field=models.TextField(
                blank=True, help_text="Prérequis recommandés pour cette formation"
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="prix",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Prix en devise locale",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="videoformation",
            name="reference",
            field=models.CharField(
                db_index=True,
                default="",
                help_text="Identifiant unique de référence (ex: FORM-001)",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="videoformation",
            name="duree",
            field=models.IntegerField(
                help_text="Durée de la formation en minutes",
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
        migrations.AlterField(
            model_name="videoformation",
            name="status",
            field=models.CharField(
                choices=[
                    ("brouillon", "Brouillon"),
                    ("publiee", "Publiée"),
                    ("archivee", "Archivée"),
                ],
                db_index=True,
                default="brouillon",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="videoformation",
            name="titre",
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name="videoformation",
            index=models.Index(
                fields=["entreprise", "categorie"],
                name="education_v_entrepr_8a7cce_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="videoformation",
            index=models.Index(
                fields=["entreprise", "niveau"], name="education_v_entrepr_55d7ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoformation",
            index=models.Index(
                fields=["entreprise", "status"], name="education_v_entrepr_af395d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="videoformation",
            index=models.Index(
                fields=["entreprise", "titre"], name="education_v_entrepr_a769d3_idx"
            ),
        ),
    ]
