# Generated by Django 5.2.10 on 2026-01-20 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "education",
            "0002_remove_videoformation_education_v_entrepr_01437c_idx_and_more",
        ),
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="videoformation",
            name="url",
        ),
        migrations.AddField(
            model_name="videoformation",
            name="video",
            field=models.FileField(
                blank=True,
                help_text="Vidéo de la formation",
                null=True,
                upload_to="formations/videos/",
            ),
        ),
        migrations.AlterField(
            model_name="videoformation",
            name="entreprise",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(class)s_set",
                to="tenants.entreprise",
            ),
        ),
    ]
